### ISSUE TITLE
appimage needed libc-ares-dev installed in order to run

### ISSUE THREAD

**Issue by christofmuc** [elk-audio/sushi#1]
Hi! Just tried to run sushi on a fresh Ubuntu 20.04 LTS install in Hyper-V, and it complained about not finding libcares.so, and wouldn't start up. 

Doing an 

    sudo apt-get install libc-ares-dev 

fixed the issues. But I guess this shouldn't be necessary given it is an appimage?

**Comment by stez-mind** [comment]
New AppImage has this linked statically, so it shouldn't be required anymore
