### ISSUE TITLE
Matt Tytel's Vital not functional

### ISSUE THREAD

**Issue by DatanoiseTV** [elk-audio/sushi#2]
Current version of the Vital Linux VST3 exits with "double free or corruption (!prev) Aborted (core dumped).
The stand alone version works. I see the get_processor_id and get_parameter_id getting the parameters and then it crashes.
![Screenshot-24-09-2021-151410](https://user-images.githubusercontent.com/6614616/134680409-210c22ef-3f28-4cc6-b311-a1a10ee737a4.png)

Update: The same happens for the LV2.
![Screenshot-24-09-2021-153816](https://user-images.githubusercontent.com/6614616/134683835-edbcd75a-871d-4a36-a137-cc0b5086afb1.png)

**Comment by stez-mind** [comment]
Thanks for the report,
could you confirm if the same plugin build works on other hosts?

**Comment by noizebox** [comment]
The fix for this bug is included in the new 0.12.0 release.

**Comment by DatanoiseTV** [comment]
> The fix for this bug is included in the new 0.12.0 release.

Now I'm getting "Failed to load tracks from Json config file" on load.

**Comment by stez-mind** [comment]
Hi @DatanoiseTV ,
what does your `/tmp/sushi.log` looks like?

**Comment by DatanoiseTV** [comment]
> Hi @DatanoiseTV , what does your `/tmp/sushi.log` looks like?

The log file gave me a hint - LV2_PATH was not defined. Perhaps also add an option to log to stderr instead of just /tmp/sushi.log?
