### ISSUE TITLE
where is `example_configs` directory?

### ISSUE THREAD

**Issue by ericfont** [elk-audio/sushi#4]
https://github.com/elk-audio/sushi#configuration-file-examples says:

> See directory example_configs for the JSON-schema definition and some example configurations.

But I can't find that directory.

**Comment by ericfont** [comment]
(I'm on x86 Ubuntu linux desktop with jack)

**Comment by noizebox** [comment]
That's looks like an oversight on out part, thanks for noticing. The example configurations for Sushi are in misc/config_files
https://github.com/elk-audio/sushi/tree/master/misc/config_files
